version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD="password"
      - MYSQL_DATABASE="assignment3_db"
    ports:
      - "3306:3306"
    volumes:
      - ./database/saved-Data:/var/lib/mysql  # Volume để lưu dữ liệu MySQL
      - ./database/db-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_app
    env_file: # Dùng env_file để load biến môi trường từ file .env
      - .env
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy  # Chờ đến khi database báo "healthy"
    networks:
      - backend-network

networks:
  backend-network: